version: '3.8'

services:
  backend1:
    build: .
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    env_file:
      - .env

  backend2:
    build: .
    environment:
      - PORT=3000
    ports:
      - "3001:3000"  # Maps backend2 to localhost:3001
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend1
      - backend2
